/**
 * Machine-readable CMS → frontend field contract.
 *
 * A new Studio field without a row here fails CI.
 * Classification:
 *   A layout/geometry   B public copy   C public media
 *   D localization      E ordering      F intentionally internal
 *   G legacy/deprecated (must not leak)
 */

export const CMS_CLASSES = ["A", "B", "C", "D", "E", "F", "G"] as const;
export type CmsClass = (typeof CMS_CLASSES)[number];

export const CMS_STATUSES = ["PASS", "INTENTIONALLY INTERNAL"] as const;
export type CmsStatus = (typeof CMS_STATUSES)[number];

export const CMS_SPAN_ENUM = ["large", "tall", "wide", "small"] as const;
export const CMS_OBJECT_TYPE_ENUM = [
  "new_build",
  "secondary",
  "private_house",
  "commercial",
] as const;
export const CMS_FIT_ENUM = ["contain", "cover"] as const;
export const CMS_MEDIA_TYPE_ENUM = ["photo", "video"] as const;

export type CmsDocumentType =
  | "project"
  | "projectMedia"
  | "inProgressFrame"
  | "inProgressBoard";

export type CmsFieldContract = {
  id: string;
  documentType: CmsDocumentType;
  field: string;
  studioTitle: string | null;
  class: CmsClass;
  intendedFrontend: boolean;
  groq: "projected" | "sort-only" | "omitted-intentional" | "derived";
  groqNeedle?: string;
  normalize: string;
  lkg: boolean;
  consumerFiles: string[];
  consumerNeedles: string[];
  behavioralTest: string;
  responsive: "exhaustive" | "sampled" | "n/a";
  status: CmsStatus;
  notes?: string;
  schemaKind?: "schema" | "image-hotspot";
  enumValues?: readonly string[];
};

export const CMS_FIELD_CONTRACT: CmsFieldContract[] = [
  {
    id: "project.orderRank",
    documentType: "project",
    field: "orderRank",
    studioTitle: null,
    class: "E",
    intendedFrontend: true,
    groq: "sort-only",
    groqNeedle: "| order(orderRank asc)",
    normalize: "array order preserved by mapSanityProject/snapshot",
    lkg: true,
    consumerFiles: ["lib/sanity/queries.ts", "components/project-dossier.tsx"],
    consumerNeedles: ["order(orderRank asc)", "projects[projectIndex - 1]"],
    behavioralTest: "order-independent-of-size",
    responsive: "n/a",
    status: "PASS",
  },
  {
    id: "project.titleUa",
    documentType: "project",
    field: "titleUa",
    studioTitle: "Назва об'єкта",
    class: "B",
    intendedFrontend: true,
    groq: "projected",
    groqNeedle: "titleUa",
    normalize: "mapSanityProject.titleUa → recordToProject.title",
    lkg: true,
    consumerFiles: ["lib/portfolio/labels.ts", "components/projects.tsx"],
    consumerNeedles: ["portfolioCardLabels", "labels.title"],
    behavioralTest: "titleUa-card-and-dossier",
    responsive: "sampled",
    status: "PASS",
  },
  {
    id: "project.objectType",
    documentType: "project",
    field: "objectType",
    studioTitle: "Тип об'єкта",
    class: "B",
    intendedFrontend: true,
    groq: "projected",
    groqNeedle: "objectType",
    normalize: "parseObjectType / categoryFromObjectType",
    lkg: true,
    consumerFiles: ["lib/portfolio/labels.ts", "components/project-dossier.tsx"],
    consumerNeedles: ["objectTypes", "dossierFacts"],
    behavioralTest: "objectType-card-meta-dossier-fact",
    responsive: "n/a",
    status: "PASS",
    enumValues: CMS_OBJECT_TYPE_ENUM,
  },
  {
    id: "project.category",
    documentType: "project",
    field: "category",
    studioTitle: "Технічна категорія",
    class: "F",
    intendedFrontend: false,
    groq: "derived",
    groqNeedle: "category",
    normalize: "fallback when objectType missing",
    lkg: true,
    consumerFiles: ["lib/sanity/map-project.ts"],
    consumerNeedles: ["parseCategory"],
    behavioralTest: "category-derived-hidden",
    responsive: "n/a",
    status: "INTENTIONALLY INTERNAL",
    notes: "Hidden/readOnly. Derived from objectType.",
  },
  {
    id: "project.locationUa",
    documentType: "project",
    field: "locationUa",
    studioTitle: "Локація",
    class: "B",
    intendedFrontend: true,
    groq: "projected",
    groqNeedle: "locationUa",
    normalize: "mapSanityProject.locationUa → recordToProject.location",
    lkg: true,
    consumerFiles: ["lib/portfolio/labels.ts", "components/project-dossier.tsx"],
    consumerNeedles: ["locationUa", "dossierFacts"],
    behavioralTest: "locationUa-dossier-and-card-context",
    responsive: "n/a",
    status: "PASS",
  },
  {
    id: "project.area",
    documentType: "project",
    field: "area",
    studioTitle: "Площа",
    class: "B",
    intendedFrontend: true,
    groq: "projected",
    groqNeedle: "area",
    normalize: "trim; omitted when empty",
    lkg: true,
    consumerFiles: ["components/projects.tsx", "lib/portfolio/labels.ts"],
    consumerNeedles: ["project-slide-area", "facts.area"],
    behavioralTest: "area-card-and-dossier",
    responsive: "sampled",
    status: "PASS",
  },
  {
    id: "project.rooms",
    documentType: "project",
    field: "rooms",
    studioTitle: "Кількість кімнат",
    class: "B",
    intendedFrontend: true,
    groq: "projected",
    groqNeedle: "rooms",
    normalize: "parseRooms 1–20; apartment meta only",
    lkg: true,
    consumerFiles: ["lib/portfolio/labels.ts"],
    consumerNeedles: ["ukRoomCardLabel", "record.rooms"],
    behavioralTest: "rooms-apartment-meta",
    responsive: "n/a",
    status: "PASS",
  },
  {
    id: "project.descriptionUa",
    documentType: "project",
    field: "descriptionUa",
    studioTitle: "Опис",
    class: "B",
    intendedFrontend: true,
    groq: "projected",
    groqNeedle: "descriptionUa",
    normalize: "asParagraphs; empty → dossier omits copy",
    lkg: true,
    consumerFiles: ["components/project-dossier.tsx"],
    consumerNeedles: ["project-dossier-copy", "descriptionParagraphs"],
    behavioralTest: "descriptionUa-optional-block",
    responsive: "n/a",
    status: "PASS",
  },
  {
    id: "project.cover",
    documentType: "project",
    field: "cover",
    studioTitle: "Обкладинка",
    class: "C",
    intendedFrontend: true,
    groq: "projected",
    groqNeedle: '"coverUrl": cover.asset->url',
    normalize: "coverUrl required",
    lkg: true,
    consumerFiles: ["components/projects.tsx"],
    consumerNeedles: ["project.cover"],
    behavioralTest: "cover-src-on-card",
    responsive: "n/a",
    status: "PASS",
  },
  {
    id: "project.gallery",
    documentType: "project",
    field: "gallery",
    studioTitle: "Галерея",
    class: "E",
    intendedFrontend: true,
    groq: "projected",
    groqNeedle: "gallery[]",
    normalize: "mapMediaItem order preserved",
    lkg: true,
    consumerFiles: ["components/project-dossier.tsx", "lib/sanity/map-project.ts"],
    consumerNeedles: ["projectMedia(project)", "goMedia"],
    behavioralTest: "gallery-order-and-count",
    responsive: "n/a",
    status: "PASS",
  },
  {
    id: "project.workTypeUa",
    documentType: "project",
    field: "workTypeUa",
    studioTitle: "Тип робіт",
    class: "B",
    intendedFrontend: true,
    groq: "projected",
    groqNeedle: "workTypeUa",
    normalize: "pickText UA/EN",
    lkg: true,
    consumerFiles: ["lib/portfolio/labels.ts"],
    consumerNeedles: ["facts.workType", "project.workType"],
    behavioralTest: "workType-dossier-fact",
    responsive: "n/a",
    status: "PASS",
  },
  {
    id: "project.durationUa",
    documentType: "project",
    field: "durationUa",
    studioTitle: "Термін виконання",
    class: "B",
    intendedFrontend: true,
    groq: "projected",
    groqNeedle: "durationUa",
    normalize: "pickText UA/EN",
    lkg: true,
    consumerFiles: ["lib/portfolio/labels.ts"],
    consumerNeedles: ["facts.duration"],
    behavioralTest: "duration-dossier-fact",
    responsive: "n/a",
    status: "PASS",
  },
  {
    id: "project.year",
    documentType: "project",
    field: "year",
    studioTitle: "Рік (застаріле)",
    class: "G",
    intendedFrontend: false,
    groq: "projected",
    groqNeedle: "year",
    normalize: "always null / omitted on Project",
    lkg: true,
    consumerFiles: ["lib/sanity/map-project.ts", "components/project-dossier.tsx"],
    consumerNeedles: ["year: null", "project-dossier-facts"],
    behavioralTest: "year-never-rendered",
    responsive: "n/a",
    status: "INTENTIONALLY INTERNAL",
    notes: "Hidden legacy. Mapper zeros it. Dossier must not show Year.",
  },
  {
    id: "project.titleEn",
    documentType: "project",
    field: "titleEn",
    studioTitle: "Назва",
    class: "D",
    intendedFrontend: true,
    groq: "projected",
    groqNeedle: "titleEn",
    normalize: "EN uses titleEn ?? titleUa",
    lkg: true,
    consumerFiles: ["lib/sanity/map-project.ts", "lib/portfolio/labels.ts"],
    consumerNeedles: ["titleEn", "pickText"],
    behavioralTest: "titleEn-fallback-and-swap",
    responsive: "n/a",
    status: "PASS",
  },
  {
    id: "project.locationEn",
    documentType: "project",
    field: "locationEn",
    studioTitle: "Location",
    class: "D",
    intendedFrontend: true,
    groq: "projected",
    groqNeedle: "locationEn",
    normalize: "EN uses locationEn ?? locationUa",
    lkg: true,
    consumerFiles: ["lib/sanity/map-project.ts"],
    consumerNeedles: ["locationEn"],
    behavioralTest: "locationEn-fallback",
    responsive: "n/a",
    status: "PASS",
  },
  {
    id: "project.descriptionEn",
    documentType: "project",
    field: "descriptionEn",
    studioTitle: "Опис",
    class: "D",
    intendedFrontend: true,
    groq: "projected",
    groqNeedle: "descriptionEn",
    normalize: "pickParagraphs EN/UA",
    lkg: true,
    consumerFiles: ["lib/sanity/map-project.ts", "components/project-dossier.tsx"],
    consumerNeedles: ["descriptionEn", "pickParagraphs"],
    behavioralTest: "descriptionEn-fallback",
    responsive: "n/a",
    status: "PASS",
  },
  {
    id: "project.workTypeEn",
    documentType: "project",
    field: "workTypeEn",
    studioTitle: "Тип робіт",
    class: "D",
    intendedFrontend: true,
    groq: "projected",
    groqNeedle: "workTypeEn",
    normalize: "pickText",
    lkg: true,
    consumerFiles: ["lib/sanity/map-project.ts"],
    consumerNeedles: ["workTypeEn"],
    behavioralTest: "workTypeEn-fallback",
    responsive: "n/a",
    status: "PASS",
  },
  {
    id: "project.durationEn",
    documentType: "project",
    field: "durationEn",
    studioTitle: "Термін виконання",
    class: "D",
    intendedFrontend: true,
    groq: "projected",
    groqNeedle: "durationEn",
    normalize: "pickText",
    lkg: true,
    consumerFiles: ["lib/sanity/map-project.ts"],
    consumerNeedles: ["durationEn"],
    behavioralTest: "durationEn-fallback",
    responsive: "n/a",
    status: "PASS",
  },
  {
    id: "project.locationKey",
    documentType: "project",
    field: "locationKey",
    studioTitle: "Місто (legacy)",
    class: "G",
    intendedFrontend: false,
    groq: "projected",
    groqNeedle: "locationKey",
    normalize: "only if no free-text location",
    lkg: true,
    consumerFiles: ["lib/sanity/map-project.ts", "lib/portfolio/labels.ts"],
    consumerNeedles: ['locationKey === "lviv"', "dict.location"],
    behavioralTest: "locationKey-legacy-fallback-only",
    responsive: "n/a",
    status: "INTENTIONALLY INTERNAL",
    notes: "Hidden. Used only when locationUa/En empty.",
  },
  {
    id: "project.slug",
    documentType: "project",
    field: "slug",
    studioTitle: "Системна адреса",
    class: "F",
    intendedFrontend: false,
    groq: "projected",
    groqNeedle: '"slug": slug.current',
    normalize: "required identity",
    lkg: true,
    consumerFiles: ["components/projects.tsx"],
    consumerNeedles: ["data-project"],
    behavioralTest: "slug-identity",
    responsive: "n/a",
    status: "INTENTIONALLY INTERNAL",
  },
  {
    id: "project.span",
    documentType: "project",
    field: "span",
    studioTitle: "Розмір картки",
    class: "A",
    intendedFrontend: true,
    groq: "projected",
    groqNeedle: "span",
    normalize: "parseSpan ?? small",
    lkg: true,
    consumerFiles: [
      "lib/portfolio-layout.ts",
      "components/projects.tsx",
      "app/globals.css",
    ],
    consumerNeedles: [
      "portfolioCardSize(project.span)",
      'data-span={layoutSpan}',
      '.project-slide[data-span="large"]',
    ],
    behavioralTest: "span-card-size-geometry",
    responsive: "exhaustive",
    status: "PASS",
    enumValues: CMS_SPAN_ENUM,
    notes: "Studio label Розмір картки. Desktop ≥1024 uses CMS flex-basis; <1024 equal peeking track is designed.",
  },
  {
    id: "project.coverPosition",
    documentType: "project",
    field: "coverPosition",
    studioTitle: "Позиція фото",
    class: "A",
    intendedFrontend: true,
    groq: "projected",
    groqNeedle: "coverPosition",
    normalize: "trim || center center",
    lkg: true,
    consumerFiles: ["components/projects.tsx"],
    consumerNeedles: ["objectPosition: project.coverPosition"],
    behavioralTest: "coverPosition-computed-style",
    responsive: "sampled",
    status: "PASS",
  },
  {
    id: "project.cover.hotspot",
    documentType: "project",
    field: "cover.hotspot",
    studioTitle: null,
    class: "F",
    intendedFrontend: false,
    groq: "omitted-intentional",
    normalize: "not mapped; superseded by coverPosition",
    lkg: false,
    consumerFiles: ["sanity/schemaTypes/project.ts"],
    consumerNeedles: ["hotspot: true"],
    behavioralTest: "hotspot-superseded-by-coverPosition",
    responsive: "n/a",
    status: "INTENTIONALLY INTERNAL",
    schemaKind: "image-hotspot",
    notes: "Sanity image hotspot UI is not the public crop source of truth.",
  },
  {
    id: "projectMedia.image",
    documentType: "projectMedia",
    field: "image",
    studioTitle: "Фото",
    class: "C",
    intendedFrontend: true,
    groq: "projected",
    groqNeedle: '"src": image.asset->url',
    normalize: "gallery src required",
    lkg: true,
    consumerFiles: ["components/project-dossier.tsx"],
    consumerNeedles: ["item.src"],
    behavioralTest: "gallery-image-src",
    responsive: "n/a",
    status: "PASS",
  },
  {
    id: "projectMedia.video",
    documentType: "projectMedia",
    field: "video",
    studioTitle: "Відео",
    class: "C",
    intendedFrontend: true,
    groq: "projected",
    groqNeedle: '"video": video.asset->url',
    normalize: "optional; real portfolio must stay empty",
    lkg: true,
    consumerFiles: ["components/project-dossier.tsx"],
    consumerNeedles: ["item.video", "PosterVideo"],
    behavioralTest: "gallery-video-optional-real-portfolio-zero",
    responsive: "n/a",
    status: "PASS",
  },
  {
    id: "projectMedia.fit",
    documentType: "projectMedia",
    field: "fit",
    studioTitle: "Відображення фото",
    class: "A",
    intendedFrontend: true,
    groq: "projected",
    groqNeedle: "fit",
    normalize: 'fit === "cover" ? cover : contain',
    lkg: true,
    consumerFiles: ["components/project-dossier.tsx", "app/globals.css"],
    consumerNeedles: ["data-fit={shown.fit}", 'data-fit="contain"'],
    behavioralTest: "gallery-fit-object-fit",
    responsive: "sampled",
    status: "PASS",
    enumValues: CMS_FIT_ENUM,
  },
  {
    id: "projectMedia.objectPosition",
    documentType: "projectMedia",
    field: "objectPosition",
    studioTitle: "Позиція фото",
    class: "A",
    intendedFrontend: true,
    groq: "projected",
    groqNeedle: "objectPosition",
    normalize: "trim || center center",
    lkg: true,
    consumerFiles: ["components/project-dossier.tsx"],
    consumerNeedles: ["objectPosition: item.objectPosition"],
    behavioralTest: "gallery-objectPosition",
    responsive: "sampled",
    status: "PASS",
  },
  {
    id: "projectMedia.thumbPosition",
    documentType: "projectMedia",
    field: "thumbPosition",
    studioTitle: "Позиція мініатюри",
    class: "A",
    intendedFrontend: true,
    groq: "projected",
    groqNeedle: "thumbPosition",
    normalize: "trim or fallback to objectPosition",
    lkg: true,
    consumerFiles: ["components/project-dossier.tsx"],
    consumerNeedles: ["item.thumbPosition ?? item.objectPosition"],
    behavioralTest: "gallery-thumbPosition",
    responsive: "n/a",
    status: "PASS",
  },
  {
    id: "projectMedia.image.hotspot",
    documentType: "projectMedia",
    field: "image.hotspot",
    studioTitle: null,
    class: "F",
    intendedFrontend: false,
    groq: "omitted-intentional",
    normalize: "not mapped; superseded by objectPosition",
    lkg: false,
    consumerFiles: ["sanity/schemaTypes/projectMedia.ts"],
    consumerNeedles: ["hotspot: true"],
    behavioralTest: "hotspot-superseded-by-objectPosition",
    responsive: "n/a",
    status: "INTENTIONALLY INTERNAL",
    schemaKind: "image-hotspot",
  },
  {
    id: "inProgressFrame.orderRank",
    documentType: "inProgressFrame",
    field: "orderRank",
    studioTitle: null,
    class: "E",
    intendedFrontend: true,
    groq: "sort-only",
    groqNeedle: "| order(orderRank asc)",
    normalize: "frames array order = viewer order",
    lkg: true,
    consumerFiles: ["lib/sanity/queries.ts", "lib/sanity/map-in-progress.ts"],
    consumerNeedles: ["order(orderRank asc)", "viewerIndexForFrame"],
    behavioralTest: "in-progress-viewer-order",
    responsive: "n/a",
    status: "PASS",
  },
  {
    id: "inProgressFrame.titleUa",
    documentType: "inProgressFrame",
    field: "titleUa",
    studioTitle: "Назва об'єкта",
    class: "B",
    intendedFrontend: true,
    groq: "projected",
    groqNeedle: "titleUa",
    normalize: "resolveInProgressTitle",
    lkg: true,
    consumerFiles: ["components/sections/in-progress.tsx", "lib/in-progress-meta.ts"],
    consumerNeedles: ["in-progress-caption-title", "resolveInProgressTitle"],
    behavioralTest: "in-progress-titleUa",
    responsive: "sampled",
    status: "PASS",
  },
  {
    id: "inProgressFrame.titleEn",
    documentType: "inProgressFrame",
    field: "titleEn",
    studioTitle: "Назва англійською",
    class: "D",
    intendedFrontend: true,
    groq: "projected",
    groqNeedle: "titleEn",
    normalize: "EN titleEn ?? titleUa",
    lkg: true,
    consumerFiles: ["lib/in-progress-meta.ts"],
    consumerNeedles: ["titleEn", "resolveInProgressTitle"],
    behavioralTest: "in-progress-titleEn-fallback",
    responsive: "n/a",
    status: "PASS",
  },
  {
    id: "inProgressFrame.area",
    documentType: "inProgressFrame",
    field: "area",
    studioTitle: "Площа, м²",
    class: "B",
    intendedFrontend: true,
    groq: "projected",
    groqNeedle: "area",
    normalize: "formatInProgressArea",
    lkg: true,
    consumerFiles: ["components/sections/in-progress.tsx", "lib/in-progress-meta.ts"],
    consumerNeedles: ["in-progress-caption-area", "formatInProgressArea"],
    behavioralTest: "in-progress-area",
    responsive: "sampled",
    status: "PASS",
  },
  {
    id: "inProgressFrame.label",
    documentType: "inProgressFrame",
    field: "label",
    studioTitle: "Внутрішня примітка",
    class: "F",
    intendedFrontend: false,
    groq: "omitted-intentional",
    normalize: "not mapped",
    lkg: false,
    consumerFiles: ["sanity/schemaTypes/inProgressFrame.ts"],
    consumerNeedles: ['title: "Внутрішня примітка"'],
    behavioralTest: "in-progress-label-not-public",
    responsive: "n/a",
    status: "INTENTIONALLY INTERNAL",
    notes: "Admin-only. Must not appear in GROQ or public UI.",
  },
  {
    id: "inProgressFrame.mediaType",
    documentType: "inProgressFrame",
    field: "mediaType",
    studioTitle: "Тип матеріалу",
    class: "C",
    intendedFrontend: true,
    groq: "projected",
    groqNeedle: "mediaType",
    normalize: "inferMediaType",
    lkg: true,
    consumerFiles: ["lib/sanity/map-in-progress.ts"],
    consumerNeedles: ["inferMediaType", "mediaType"],
    behavioralTest: "in-progress-mediaType",
    responsive: "n/a",
    status: "PASS",
    enumValues: CMS_MEDIA_TYPE_ENUM,
  },
  {
    id: "inProgressFrame.still",
    documentType: "inProgressFrame",
    field: "still",
    studioTitle: "Фото",
    class: "C",
    intendedFrontend: true,
    groq: "projected",
    groqNeedle: "still.asset->url",
    normalize: "src from still or poster",
    lkg: true,
    consumerFiles: ["lib/sanity/queries.ts", "components/sections/in-progress.tsx"],
    consumerNeedles: ["coalesce(poster.asset->url, still.asset->url)", "item.src"],
    behavioralTest: "in-progress-still",
    responsive: "n/a",
    status: "PASS",
  },
  {
    id: "inProgressFrame.video",
    documentType: "inProgressFrame",
    field: "video",
    studioTitle: "Відео",
    class: "C",
    intendedFrontend: true,
    groq: "projected",
    groqNeedle: '"video": video.asset->url',
    normalize: "full viewer source",
    lkg: true,
    consumerFiles: ["components/sections/in-progress-viewer.tsx"],
    consumerNeedles: ["mp4={item.video}"],
    behavioralTest: "in-progress-full-video-in-viewer",
    responsive: "sampled",
    status: "PASS",
  },
  {
    id: "inProgressFrame.previewVideo",
    documentType: "inProgressFrame",
    field: "previewVideo",
    studioTitle: "Прев’ю для головної (авто)",
    class: "F",
    intendedFrontend: false,
    groq: "projected",
    groqNeedle: '"previewVideo": previewVideo.asset->url',
    normalize: "homepage panel prefers previewVideo ?? video",
    lkg: true,
    consumerFiles: ["components/sections/in-progress.tsx"],
    consumerNeedles: ["item.previewVideo ?? item.video"],
    behavioralTest: "preview-vs-full-distinct",
    responsive: "sampled",
    status: "INTENTIONALLY INTERNAL",
    notes: "Hidden auto derivative. Public panel consumes it; client does not edit.",
  },
  {
    id: "inProgressFrame.poster",
    documentType: "inProgressFrame",
    field: "poster",
    studioTitle: "Обкладинка відео",
    class: "C",
    intendedFrontend: true,
    groq: "projected",
    groqNeedle: "poster.asset->url",
    normalize: "src coalesce poster then still",
    lkg: true,
    consumerFiles: ["lib/sanity/queries.ts"],
    consumerNeedles: ["coalesce(poster.asset->url, still.asset->url)"],
    behavioralTest: "in-progress-poster",
    responsive: "n/a",
    status: "PASS",
  },
  {
    id: "inProgressFrame.objectPosition",
    documentType: "inProgressFrame",
    field: "objectPosition",
    studioTitle: "Позиція фото",
    class: "A",
    intendedFrontend: true,
    groq: "projected",
    groqNeedle: "objectPosition",
    normalize: "trim || center center",
    lkg: true,
    consumerFiles: [
      "components/sections/in-progress.tsx",
      "components/sections/in-progress-viewer.tsx",
    ],
    consumerNeedles: [
      "objectPosition={item.objectPosition}",
      "objectPosition: item.objectPosition",
    ],
    behavioralTest: "in-progress-objectPosition",
    responsive: "sampled",
    status: "PASS",
  },
  {
    id: "inProgressFrame.frameId",
    documentType: "inProgressFrame",
    field: "frameId",
    studioTitle: "Системний ідентифікатор",
    class: "F",
    intendedFrontend: false,
    groq: "projected",
    groqNeedle: '"frameId": frameId.current',
    normalize: "item.id",
    lkg: true,
    consumerFiles: ["lib/sanity/map-in-progress.ts"],
    consumerNeedles: ["doc.frameId"],
    behavioralTest: "frameId-identity",
    responsive: "n/a",
    status: "INTENTIONALLY INTERNAL",
  },
  {
    id: "inProgressFrame.still.hotspot",
    documentType: "inProgressFrame",
    field: "still.hotspot",
    studioTitle: null,
    class: "F",
    intendedFrontend: false,
    groq: "omitted-intentional",
    normalize: "not mapped; superseded by objectPosition",
    lkg: false,
    consumerFiles: ["sanity/schemaTypes/inProgressFrame.ts"],
    consumerNeedles: ["hotspot: true"],
    behavioralTest: "hotspot-superseded-by-objectPosition",
    responsive: "n/a",
    status: "INTENTIONALLY INTERNAL",
    schemaKind: "image-hotspot",
  },
  {
    id: "inProgressFrame.poster.hotspot",
    documentType: "inProgressFrame",
    field: "poster.hotspot",
    studioTitle: null,
    class: "F",
    intendedFrontend: false,
    groq: "omitted-intentional",
    normalize: "not mapped; superseded by objectPosition",
    lkg: false,
    consumerFiles: ["sanity/schemaTypes/inProgressFrame.ts"],
    consumerNeedles: ["hotspot: true"],
    behavioralTest: "hotspot-superseded-by-objectPosition",
    responsive: "n/a",
    status: "INTENTIONALLY INTERNAL",
    schemaKind: "image-hotspot",
  },
  {
    id: "inProgressBoard.blinds",
    documentType: "inProgressBoard",
    field: "blinds",
    studioTitle: "Панелі зліва направо",
    class: "E",
    intendedFrontend: true,
    groq: "projected",
    groqNeedle: '"boardIds": blinds[]->frameId.current',
    normalize: "parseBoardIds length 4 unique",
    lkg: true,
    consumerFiles: ["components/sections/in-progress.tsx", "lib/sanity/map-in-progress.ts"],
    consumerNeedles: ["boardIds", "compositionFromRecord"],
    behavioralTest: "board-order-left-to-right",
    responsive: "sampled",
    status: "PASS",
  },
];

export function schemaFieldsFor(documentType: CmsDocumentType) {
  return CMS_FIELD_CONTRACT.filter(
    (row) => row.documentType === documentType && row.schemaKind !== "image-hotspot"
  );
}

export function intendedFrontendFields() {
  return CMS_FIELD_CONTRACT.filter((row) => row.intendedFrontend);
}
